@TodoTracker_HostAddress = http://localhost:5187

### Получить все проекты
GET {{TodoTracker_HostAddress}}/api/projects
Accept: application/json

### Получить проект
GET {{TodoTracker_HostAddress}}/api/projects/01a0af50-591e-77c0-9aef-ae60b9e7cc44
Accept: application/json

### Создать проект
POST {{TodoTracker_HostAddress}}/api/projects
Content-Type: application/json

{
  "name": "Учёба",
  "description": "Курсы и книги"
}
### Создать проект с пустым именем
POST {{TodoTracker_HostAddress}}/api/projects
Content-Type: application/json

{
  "name": "",
  "description": "Тест валидации"
}
### Создать проект без имени
POST {{TodoTracker_HostAddress}}/api/projects
Content-Type: application/json

{
  "description": "Тест валидации"
}



### Регистрация
POST {{TodoTracker_HostAddress}}/api/users
Content-Type: application/json

{
  "login": "alice",
  "password": "password123",
  "name": "Alice"
}

### Регистрация
POST {{TodoTracker_HostAddress}}/api/users
Content-Type: application/json

{
  "login": "bob",
  "password": "password123",
  "name": "bob"
}

### Повторная регистрация (должен быть 409)
POST {{TodoTracker_HostAddress}}/api/users
Content-Type: application/json

{
  "login": "alice",
  "password": "anotherpass",
  "name": "Alice 2"
}

### Регистрация с коротким паролем (должен быть 400)
POST {{TodoTracker_HostAddress}}/api/users
Content-Type: application/json

{
  "login": "bob",
  "password": "123",
  "name": "Bob"
}




### Успешный логин alice
POST {{TodoTracker_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "login": "alice",
  "password": "password123"
}

### Успешный логин bob
POST {{TodoTracker_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "login": "bob",
  "password": "password123"
}

### Неверный пароль (должен быть 401)
POST {{TodoTracker_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "login": "alice",
  "password": "wrongpassword"
}

### Несуществующий логин (должен быть 401)
POST {{TodoTracker_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "login": "nonexistent",
  "password": "whatever123"
}


### Логин
POST {{TodoTracker_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "login": "alice",
  "password": "password123"
}

###
GET {{TodoTracker_HostAddress}}/api/projects


###
GET {{TodoTracker_HostAddress}}/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMWEwYzhkYy1hYzdlLTc5MzctYWQzYi0xZDUxMGFjMzJjN2EiLCJsb2dpbiI6ImFsaWNlIiwiZXhwIjoxNzkwMjQ1Mjc4LCJpc3MiOiJUb2RvVHJhY2tlciIsImF1ZCI6IlRvZG9UcmFja2VyQ2xpZW50In0.DGxObMltQo-lpETK7yExiMPG_OaTjkyqlSxRhuAl1Lk

###
GET {{TodoTracker_HostAddress}}/api/projects
Authorization: Bearer invalid.token.here

"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMWEwYzhkYy1hYzdlLTc5MzctYWQzYi0xZDUxMGFjMzJjN2EiLCJsb2dpbiI6ImFsaWNlIiwiZXhwIjoxNzkwMjQ1Mjc4LCJpc3MiOiJUb2RvVHJhY2tlciIsImF1ZCI6IlRvZG9UcmFja2VyQ2xpZW50In0.DGxObMltQo-lpETK7yExiMPG_OaTjkyqlSxRhuAl1Lk"


###
POST {{TodoTracker_HostAddress}}/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMWEwYzhkYy1hYzdlLTc5MzctYWQzYi0xZDUxMGFjMzJjN2EiLCJsb2dpbiI6ImFsaWNlIiwiZXhwIjoxNzkwMjQ1Mjc4LCJpc3MiOiJUb2RvVHJhY2tlciIsImF1ZCI6IlRvZG9UcmFja2VyQ2xpZW50In0.DGxObMltQo-lpETK7yExiMPG_OaTjkyqlSxRhuAl1Lk
Content-Type: application/json

{
  "name": "Тестовый проект",
  "description": "Проверка OwnerId"
}

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMWEwZDJkYS0yYTdkLTczNjgtYTE4Yi00NzM4N2YxOWIyNGUiLCJsb2dpbiI6ImJvYiIsImV4cCI6MTc5MDI0NzUzMiwiaXNzIjoiVG9kb1RyYWNrZXIiLCJhdWQiOiJUb2RvVHJhY2tlckNsaWVudCJ9.eaRZsc2B3Y9m69vJNPczf_PADWiYSHKNKJ9xwBTbySU


###
GET {{TodoTracker_HostAddress}}/api/projects




Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMWEwZDJkYS0yYTdkLTczNjgtYTE4Yi00NzM4N2YxOWIyNGUiLCJsb2dpbiI6ImJvYiIsImV4cCI6MTc5MDI0NzUzMiwiaXNzIjoiVG9kb1RyYWNrZXIiLCJhdWQiOiJUb2RvVHJhY2tlckNsaWVudCJ9.eaRZsc2B3Y9m69vJNPczf_PADWiYSHKNKJ9xwBTbySU



###
GET {{TodoTracker_HostAddress}}/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMWEwYzhkYy1hYzdlLTc5MzctYWQzYi0xZDUxMGFjMzJjN2EiLCJsb2dpbiI6ImFsaWNlIiwiZXhwIjoxNzkwMjQ1Mjc4LCJpc3MiOiJUb2RvVHJhY2tlciIsImF1ZCI6IlRvZG9UcmFja2VyQ2xpZW50In0.DGxObMltQo-lpETK7yExiMPG_OaTjkyqlSxRhuAl1Lk



###
GET {{TodoTracker_HostAddress}}/api/projects/01a0d2d8-5508-7a62-b8e9-b25aac6385e0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMWEwZDJkYS0yYTdkLTczNjgtYTE4Yi00NzM4N2YxOWIyNGUiLCJsb2dpbiI6ImJvYiIsImV4cCI6MTc5MDI0NzUzMiwiaXNzIjoiVG9kb1RyYWNrZXIiLCJhdWQiOiJUb2RvVHJhY2tlckNsaWVudCJ9.eaRZsc2B3Y9m69vJNPczf_PADWiYSHKNKJ9xwBTbySU

